export type MusicSet = {
  id: string;
  title: string;
  artist: string;
  date: string;
  venue?: string;
  description?: string;
  duration?: string;
  src: string;
  artwork?: string;
  peaks?: string; // URL to peaks JSON generated by scripts/generate-peaks.mjs
};

// Add your sets here. src should be the public Cloudflare R2 URL for the MP3.
export const sets: MusicSet[] = [
  {
    id: "set-002-til",
    title: "Form:at 002",
    artist: "t.i.l.",
    date: "2026-04-24",
    venue: "Find the red door, Glasgow",
    description:
      "Opening transmission for sequence 002. Establishing the initial connection with deep, hypnotic dub techno.",
    duration: "45:18",
    src: "https://pub-e15e86da649d4c91b6666141bfe67664.r2.dev/002/Form_at%20002%20-%20t.i.l.mp3",
    peaks: "https://pub-e15e86da649d4c91b6666141bfe67664.r2.dev/002/Form_at%20002%20-%20t.i.l.json",
    artwork: "sets/002",
  },
  {
    id: "set-002-hubey",
    title: "Form:at 002",
    artist: "hubey",
    date: "2026-04-24",
    venue: "Find the red door, Glasgow",
    description:
      "Mid-sequence escalation. Elevating the frequency with a high-energy blend of acid, electro, and driving grooves that took total control of the dancefloor.",
    duration: "1:31:55",
    src: "https://pub-e15e86da649d4c91b6666141bfe67664.r2.dev/002/Form_at%20002%20-%20hubey.mp3",
    peaks: "https://pub-e15e86da649d4c91b6666141bfe67664.r2.dev/002/Form_at%20002%20-%20hubey.json",
    artwork: "sets/002",
  },
  {
    id: "set-002-brandon-lee-vear",
    title: "Form:at 002",
    artist: "Brandon Lee Vear",
    date: "2026-04-24",
    venue: "Find the red door, Glasgow",
    description:
      "External operator integrated. A two-hour sustained transmission of deep, hypnotic techno, locking the dancefloor into a continuous loop during peak system hours.",
    duration: "2:01:55",
    src: "https://pub-e15e86da649d4c91b6666141bfe67664.r2.dev/002/Form_at%20002%20-%20Brandon%20Lee%20Vear.mp3.mp3",
    peaks:
      "https://pub-e15e86da649d4c91b6666141bfe67664.r2.dev/002/Form_at%20002%20-%20Brandon%20Lee%20Vear.mp3.json",
    artwork: "sets/002",
  },
  {
    id: "set-002-julz-lever",
    title: "Form:at 002",
    artist: "Julz Lever",
    date: "2026-04-24",
    venue: "Find the red door, Glasgow",
    description:
      "Closing protocol for sequence 002. High-fidelity techno pushing the system's architecture to its absolute limit.",
    duration: "1:39:30",
    src: "https://pub-e15e86da649d4c91b6666141bfe67664.r2.dev/002/Form_at%20002%20-%20Julz%20Lever.mp3",
    peaks:
      "https://pub-e15e86da649d4c91b6666141bfe67664.r2.dev/002/Form_at%20002%20-%20Julz%20Lever.json",
    artwork: "sets/002",
  },
];

export function getSet(id: string): MusicSet | undefined {
  return sets.find((s) => s.id === id);
}
