#!/usr/bin/env tsx
/**
 * Regenerates `packages/data/src/sets.generated.ts` — a build-time snapshot
 * of the `sets` D1 table, newest upload first. COMMITTED to git (not
 * gitignored): `pnpm dev`, tsc, and every CI job (`static`/`knip`/`unit`/
 * `e2e`) read whatever's currently committed and need no Cloudflare
 * credentials to do so. Only `deploy.yml`'s `deploy` job (apps/web) runs
 * this script fresh, immediately before the production build, so the
 * deployed bundle always reflects the current table — see sets.ts's own
 * comment for the full offline-survival reasoning this exists for.
 *
 * Fails loudly (non-zero exit) on any query failure or unexpected output
 * shape — a broken build here is far better than silently shipping an
 * empty catalogue as the offline fallback.
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { mapD1RowToMusicSet } from "@form-at/data/sets";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = join(__dirname, "..", "..", "..", "packages", "data", "src", "sets.generated.ts");

type SetRow = {
  id: string;
  title: string;
  artist: string;
  date: string;
  venue: string | null;
  description: string | null;
  duration: string | null;
  src: string;
  artwork: string | null;
  peaks: string | null;
  size_bytes: number | null;
  created_at: number;
};

function queryD1(): SetRow[] {
  let stdout: string;
  try {
    stdout = execFileSync(
      "npx",
      [
        "wrangler",
        "d1",
        "execute",
        "form-at-analytics",
        "--remote",
        "--json",
        "--command",
        "SELECT * FROM sets ORDER BY created_at DESC",
      ],
      { encoding: "utf-8" },
    );
  } catch (err) {
    throw new Error(
      `generate-sets-snapshot: wrangler d1 execute failed — is CLOUDFLARE_API_TOKEN/CLOUDFLARE_ACCOUNT_ID set? (${err})`,
    );
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(stdout);
  } catch (err) {
    throw new Error(`generate-sets-snapshot: wrangler returned non-JSON output (${err})`);
  }

  if (
    !Array.isArray(parsed) ||
    parsed.length === 0 ||
    typeof parsed[0] !== "object" ||
    parsed[0] === null ||
    !Array.isArray((parsed[0] as { results?: unknown }).results)
  ) {
    throw new Error(
      "generate-sets-snapshot: unexpected wrangler --json shape — expected [{ results: [...] }]",
    );
  }

  return (parsed[0] as { results: SetRow[] }).results;
}

function writeSnapshot(rows: SetRow[]) {
  const sets = rows.map(mapD1RowToMusicSet);
  const body = `// AUTO-GENERATED by \`pnpm generate-sets-snapshot\`
// (apps/web/scripts/generate-sets-snapshot.ts). Committed to git deliberately
// — see the comment above \`sets\` in packages/data/src/sets.ts for why. Do
// not hand-edit; this is overwritten the next time the script runs.
import type { MusicSet } from "./sets";

export const sets: MusicSet[] = ${JSON.stringify(sets, null, 2)};
`;
  writeFileSync(OUT_PATH, body);

  // JSON.stringify always quotes object keys — Biome's style doesn't, for
  // plain identifier keys. CI's per-package `lint` runs `biome check`
  // read-only (no --write), so a quoted-key file fails it outright rather
  // than just looking untidy; this can't depend on whoever regenerates the
  // file remembering to run `pnpm check` afterward. Self-format on every
  // run instead, so the committed output is always correct regardless of
  // how it was produced.
  execFileSync("npx", ["biome", "check", "--write", OUT_PATH], { stdio: "inherit" });

  console.log(`✓ ${OUT_PATH} (${sets.length} sets)`);
}

writeSnapshot(queryD1());
