/// <reference types="@cloudflare/workers-types" />
import { sets } from "./sets.generated";

// THE canonical audio host (TECH_DEBT 19 — custom domain in front of the
// form-at-sets R2 bucket; no rate limit, Cloudflare edge caching, the
// production-recommended path).
//
// Worker-safe module (no window/navigator, and the one import above is a
// plain data array with zero browser globals of its own): `apps/web/app/sw.ts`
// imports the hostname for its audio route matcher and type-checks under
// WebWorker libs. Every code reference to the audio host goes through these
// consts — the ONE place that changes if the host ever moves again.
// Exceptions that can't import TS: `public/_headers` (static file — carries a
// keep-in-sync comment pointing here).
export const AUDIO_HOST = "cdn.formatglasgow.com";
export const AUDIO_ORIGIN = `https://${AUDIO_HOST}`;

export type MusicSet = {
  id: string;
  title: string;
  artist: string;
  date: string;
  // The DJ who played this set — a foreign key into `./djs`'s `DJ.id`,
  // chosen from a dropdown at upload (never inferred from `artist`: that
  // free-text string has no reliable normalization back to a DJ id —
  // `slugify("t.i.l.")` produces "t-i-l", not the real id "til", confirmed
  // against this catalogue's own resident). Optional because it's still
  // nullable server-side for defense in depth, but every real set has one.
  djId?: string;
  // The event this set was recorded at — a foreign key into `./events`'s
  // `Event.id`, chosen from a dropdown at upload. Genuinely nullable: a set
  // with no event (a future studio mix) is a real case, not a data gap.
  // `getCityForSet` (./events) is how a set's display location is resolved —
  // never derive it by matching `date` against an event's `date`, which
  // isn't enforced anywhere and is exactly the kind of implicit join this
  // field replaces.
  eventId?: string;
  description?: string;
  duration?: string;
  src: string;
  artwork?: string;
  peaks?: string; // URL to peaks JSON generated by scripts/generate-peaks.mjs
  // The as-uploaded R2 original — the fallback source `Image.tsx` renders
  // when `artwork`'s optimized variants don't exist yet. `optimize-images.ts`
  // generates those variants for every uploaded set on each build. Always
  // undefined for the 4 legacy sets, whose optimized variants are already
  // committed — they never need this.
  artworkOriginalUrl?: string;
  // Display-only hint for the pre-download save_for_offline label. Authored
  // manually from `curl -I <src> | grep -i content-length`. HEAD at download
  // time is the source of truth for quota pre-flight — this field is never
  // consulted for correctness, only for UI. Optional: missing → button shows
  // a generic `[ save_for_offline ]` label.
  sizeBytes?: number;
};

// The catalogue's authoritative store is a D1 `sets` table.
// `sets.generated.ts` is a build-time snapshot of it, regenerated by
// `pnpm generate-sets-snapshot` and COMMITTED to git — never gitignore it, or
// `pnpm dev`, tsc and every CI job start needing Cloudflare credentials. Only
// `deploy.yml`'s `deploy` job regenerates it, immediately before the production
// build.
//
// It's also the offline-survival baseline: the full catalogue the public site
// falls back to with zero network dependency when a live D1 fetch fails or
// hasn't resolved yet. See `mergeSets` below for the live-overlay half.
export { sets };

export function getSet(id: string): MusicSet | undefined {
  return sets.find((s) => s.id === id);
}

// Raw shape of a row from the `sets` D1 table — snake_case columns, plus
// `peaks_status`, which exists for the upload feature but isn't part of the
// public `MusicSet` type at all — no call site needs it.
// `artwork_original_url` IS mapped through (see `artworkOriginalUrl` on
// `MusicSet`) — `Image.tsx`'s fallback is its consumer.
//
// `venue` is deliberately absent here even though the column still exists in
// D1 (schema.sql) — nothing reads it anymore (see `MusicSet.eventId`'s own
// comment for why), so it's dead going forward rather than dropped outright;
// a `SELECT *` still returns it, it's just never mapped through.
type SetRow = {
  id: string;
  title: string;
  artist: string;
  date: string;
  dj_id: string | null;
  event_id: string | null;
  description: string | null;
  duration: string | null;
  src: string;
  artwork: string | null;
  artwork_original_url: string | null;
  peaks: string | null;
  size_bytes: number | null;
  created_at: number;
};

// Shared by the runtime fetch functions below AND
// apps/web/scripts/generate-sets-snapshot.ts (imported from this package), so
// the D1-row-to-MusicSet mapping exists in exactly one place.
export function mapD1RowToMusicSet(row: SetRow): MusicSet {
  return {
    id: row.id,
    title: row.title,
    artist: row.artist,
    date: row.date,
    djId: row.dj_id ?? undefined,
    eventId: row.event_id ?? undefined,
    description: row.description ?? undefined,
    duration: row.duration ?? undefined,
    src: row.src,
    artwork: row.artwork ?? undefined,
    artworkOriginalUrl: row.artwork_original_url ?? undefined,
    peaks: row.peaks ?? undefined,
    sizeBytes: row.size_bytes ?? undefined,
  };
}

// The current, complete state of the `sets` table — newest upload first.
// Callers merge this with the build-time snapshot via `mergeSets` rather than
// using it alone, since that merge is what makes the D1-unreachable case
// degrade to "render the snapshot" instead of a bespoke second code path.
export async function fetchUploadedSets(db: D1Database): Promise<MusicSet[]> {
  const { results } = await db.prepare("SELECT * FROM sets ORDER BY created_at DESC").all<SetRow>();
  return results.map(mapD1RowToMusicSet);
}

// Backs the tombstone check `mergeSets` and `fetchSetById` use to stop a
// deleted set's still-committed snapshot copy from outliving the deploy that
// would otherwise regenerate it (PWA_PROGRESS.md's PR6 entry traces the gap;
// the "narrower SSR-only case" addendum there is this). Reuses
// `admin_deleted_sets` — PR6's own delete-audit log — rather than a new
// table: a row with `restored_at IS NULL` is, precisely, "currently deleted,
// not since restored", which is exactly what a tombstone needs. Restoring a
// set already sets `restored_at`, and a later re-delete writes a fresh
// unrestored row, so this stays correct across any number of delete/restore
// cycles for the same id with no extra bookkeeping.
//
// Never throws — resolves to an empty set on any failure. This read is pure
// upside when it works and must be safe to lose: a stale snapshot entry
// still showing is the pre-existing, accepted behaviour; blanking a request
// because THIS query failed would be a regression this change must not
// introduce. Callers get today's exact behaviour back for free by treating
// an empty set as "nothing known to be deleted", not by handling failure
// specially themselves.
export async function fetchDeletedSetIds(db: D1Database): Promise<Set<string>> {
  try {
    const { results } = await db
      .prepare("SELECT DISTINCT set_id FROM admin_deleted_sets WHERE restored_at IS NULL")
      .all<{ set_id: string }>();
    return new Set(results.map((r) => r.set_id));
  } catch {
    return new Set();
  }
}

// D1 (live) wins over the static snapshot — the same precedence `mergeSets`
// below applies, and deliberately consistent with it. Checking the snapshot
// first would let the list page (via `mergeSets`, live-wins) and this detail
// lookup show DIFFERENT data for the same id: a direct
// `UPDATE sets SET ... WHERE id = ?` against production is a viable stopgap
// for a typo fix, and snapshot-first would keep serving the old value here
// until the next deploy regenerated the snapshot, while the list page already
// showed the correction. Falling back to the snapshot only on a genuine D1
// miss keeps both paths honest about the same fact: D1 is authoritative, the
// snapshot is the offline/outage fallback.
//
// The row query and the tombstone check run in parallel (Promise.all), not
// sequentially — same latency as before this existed. A row found is always
// authoritative regardless of tombstone state (the `sets` table itself is
// the one ground truth; a tombstone is metadata ABOUT it, never a competing
// source). Only when D1 has no row at all does the tombstone decide the
// fallback: genuinely deleted → undefined, so the route's existing
// `if (!set) throw notFound()` fires instead of silently rendering (and, for
// a set, PLAYING — deletion never touches R2) a copy that shouldn't exist
// anymore. Anything else missing-and-not-tombstoned still falls back to the
// snapshot exactly as before.
export async function fetchSetById(db: D1Database, id: string): Promise<MusicSet | undefined> {
  const [row, deletedIds] = await Promise.all([
    db.prepare("SELECT * FROM sets WHERE id = ?").bind(id).first<SetRow>(),
    fetchDeletedSetIds(db),
  ]);
  if (row) return mapD1RowToMusicSet(row);
  if (deletedIds.has(id)) return undefined;
  return getSet(id);
}

// Combines a live D1 fetch with the build-time snapshot, deduping by id
// (live wins on overlap, same precedence `fetchSetById` above applies —
// D1 is authoritative, the snapshot is the offline/outage fallback, not a
// competing source). Concatenating live-then-snapshot (rather than a real
// merge-sort) is correct as long as every live-only entry is newer than
// every snapshot entry, which holds by construction: `live` reflects the
// table's current state and `snapshot` reflects an earlier point in time,
// so anything not yet in the snapshot was necessarily uploaded after it was
// generated.
//
// `deletedIds` (default empty — today's exact behaviour when omitted or
// when the caller's own tombstone read failed) filters the SNAPSHOT half
// only, and only for ids not already contributed by `live`: a live entry
// always wins regardless of tombstone state, same reasoning as
// `fetchSetById` above. This is what stops a deleted set's snapshot copy
// from surviving a union that otherwise has no way to express "this id
// should no longer exist" — see the PR6 entry in PWA_PROGRESS.md this
// closes the narrower half of. Callers compute `deletedIds` fresh on every
// call (`fetchDeletedSetIds`, no caching) — `mergeSets` itself holds no
// state between calls, so a delete-then-restore-then-delete-again sequence
// can never leak stale state from one cycle into the next.
export function mergeSets(
  live: MusicSet[],
  snapshot: MusicSet[],
  deletedIds: ReadonlySet<string> = new Set(),
): MusicSet[] {
  const seen = new Set<string>();
  const merged: MusicSet[] = [];
  for (const set of live) {
    if (seen.has(set.id)) continue;
    seen.add(set.id);
    merged.push(set);
  }
  for (const set of snapshot) {
    if (seen.has(set.id) || deletedIds.has(set.id)) continue;
    seen.add(set.id);
    merged.push(set);
  }
  return merged;
}
