/// <reference types="@cloudflare/workers-types" />
import { sets } from "./sets.generated";

// THE canonical audio host (TECH_DEBT 19 — custom domain in front of the
// form-at-sets R2 bucket; no rate limit, Cloudflare edge caching, the
// production-recommended path).
//
// Worker-safe module (no window/navigator, and the one import above is a
// plain data array with zero browser globals of its own): `apps/web/app/sw.ts`
// imports the hostname for its audio route matcher and type-checks under
// WebWorker libs. Every code reference to the audio host goes through these
// consts — the ONE place that changes if the host ever moves again.
// Exceptions that can't import TS: `public/_headers` (static file — carries a
// keep-in-sync comment pointing here).
export const AUDIO_HOST = "cdn.formatglasgow.com";
export const AUDIO_ORIGIN = `https://${AUDIO_HOST}`;

export type MusicSet = {
  id: string;
  title: string;
  artist: string;
  date: string;
  venue?: string;
  description?: string;
  duration?: string;
  src: string;
  artwork?: string;
  peaks?: string; // URL to peaks JSON generated by scripts/generate-peaks.mjs
  // The as-uploaded R2 original (admin set-upload feature, PR4) — the
  // fallback source `Image.tsx` renders when `artwork`'s optimized variants
  // don't exist (true for every uploaded set until PR5 teaches
  // optimize-images.mjs to generate them). Always undefined for the 4
  // legacy sets (migrated before this field existed, and their optimized
  // variants are already committed — they never need this).
  artworkOriginalUrl?: string;
  // Display-only hint for the pre-download save_for_offline label. Authored
  // manually from `curl -I <src> | grep -i content-length`. HEAD at download
  // time is the source of truth for quota pre-flight — this field is never
  // consulted for correctness, only for UI. Optional: missing → button shows
  // a generic `[ save_for_offline ]` label.
  sizeBytes?: number;
};

// `sets` is no longer a hand-maintained literal — the catalogue moved to a
// D1 `sets` table (admin set-upload feature, 2026-08). `sets.generated.ts`
// (imported above) is a build-time snapshot regenerated from that table by
// `pnpm generate-sets-snapshot` (apps/web/scripts/generate-sets-snapshot.ts)
// and COMMITTED to git (not gitignored) — deliberately, so `pnpm dev`, tsc,
// and every CI job keep working with zero Cloudflare credentials, exactly
// like today. Only `deploy.yml`'s `deploy` job (apps/web) regenerates it
// live immediately before the production build; nothing else touches it.
//
// This snapshot is the offline-survival baseline: it's what the public
// catalogue falls back to, in full, with zero network dependency, if a live
// D1 fetch fails or hasn't happened yet (first-ever hydration, an evicted
// cache, or any device that's simply offline) — see `fetchUploadedSets`/
// `mergeSets` below for the live-overlay half of that design.
export { sets };

export function getSet(id: string): MusicSet | undefined {
  return sets.find((s) => s.id === id);
}

// Raw shape of a row from the `sets` D1 table — snake_case columns, plus
// `peaks_status`, which exists for the upload feature but isn't part of the
// public `MusicSet` type at all — no call site needs it.
// `artwork_original_url` IS mapped through (see `artworkOriginalUrl` on
// `MusicSet`) — it was excluded here originally, before there was a
// consumer for it; PR4's `Image.tsx` fallback is that consumer.
type SetRow = {
  id: string;
  title: string;
  artist: string;
  date: string;
  venue: string | null;
  description: string | null;
  duration: string | null;
  src: string;
  artwork: string | null;
  artwork_original_url: string | null;
  peaks: string | null;
  size_bytes: number | null;
  created_at: number;
};

// Shared by the runtime fetch functions below AND
// apps/web/scripts/generate-sets-snapshot.ts (imported from this package), so
// the D1-row-to-MusicSet mapping exists in exactly one place.
export function mapD1RowToMusicSet(row: SetRow): MusicSet {
  return {
    id: row.id,
    title: row.title,
    artist: row.artist,
    date: row.date,
    venue: row.venue ?? undefined,
    description: row.description ?? undefined,
    duration: row.duration ?? undefined,
    src: row.src,
    artwork: row.artwork ?? undefined,
    artworkOriginalUrl: row.artwork_original_url ?? undefined,
    peaks: row.peaks ?? undefined,
    sizeBytes: row.size_bytes ?? undefined,
  };
}

// The current, complete state of the `sets` table — newest upload first.
// When this succeeds it's already a superset of the build-time snapshot
// (nothing is ever removed from this table today, so live state only grows
// relative to whatever was true when the snapshot was generated); callers
// still merge it with the snapshot via `mergeSets` rather than using it
// alone, since that merge is what makes the D1-unreachable case degrade to
// "render the snapshot" instead of a bespoke second code path.
export async function fetchUploadedSets(db: D1Database): Promise<MusicSet[]> {
  const { results } = await db.prepare("SELECT * FROM sets ORDER BY created_at DESC").all<SetRow>();
  return results.map(mapD1RowToMusicSet);
}

// D1 (live) wins over the static snapshot — same precedence `mergeSets`
// below applies, and deliberately consistent with it. Fixed from an earlier
// version of this function that checked the snapshot first and only queried
// D1 on a miss: that meant the list page (via `mergeSets`, live-wins) and
// this detail lookup (static-wins) could show DIFFERENT data for the same
// id — and since the documented stopgap for a typo fix is a direct
// `UPDATE sets SET ... WHERE id = ?` against production (edit/delete proper
// is deferred, see PR6 notes), static-wins would have kept serving the old
// value on the detail page until the next deploy regenerated the snapshot,
// while the list page already showed the correction. Falling back to the
// snapshot only on a genuine D1 miss keeps both paths honest about the same
// fact: D1 is authoritative, the snapshot is the offline/outage fallback.
export async function fetchSetById(db: D1Database, id: string): Promise<MusicSet | undefined> {
  const row = await db.prepare("SELECT * FROM sets WHERE id = ?").bind(id).first<SetRow>();
  return row ? mapD1RowToMusicSet(row) : getSet(id);
}

// Combines a live D1 fetch with the build-time snapshot, deduping by id
// (live wins on overlap, same precedence `fetchSetById` above applies —
// D1 is authoritative, the snapshot is the offline/outage fallback, not a
// competing source). Concatenating live-then-snapshot (rather than a real
// merge-sort) is correct as long as every live-only entry is newer than
// every snapshot entry, which holds by construction: `live` reflects the
// table's current state and `snapshot` reflects an earlier point in time,
// so anything not yet in the snapshot was necessarily uploaded after it was
// generated.
export function mergeSets(live: MusicSet[], snapshot: MusicSet[]): MusicSet[] {
  const seen = new Set<string>();
  const merged: MusicSet[] = [];
  for (const set of [...live, ...snapshot]) {
    if (seen.has(set.id)) continue;
    seen.add(set.id);
    merged.push(set);
  }
  return merged;
}
