// AUTO-GENERATED by `pnpm generate-sets-snapshot`
// (apps/web/scripts/generate-sets-snapshot.ts). Committed to git deliberately
// — see the comment above `sets` in packages/data/src/sets.ts for why. Do
// not hand-edit; this is overwritten the next time the script runs.
import type { MusicSet } from "./sets";

export const sets: MusicSet[] = [
  {
    id: "set-002-til",
    title: "Form:at 002",
    artist: "t.i.l.",
    date: "2026-04-24",
    venue: "Find the red door, Glasgow",
    description:
      "Opening transmission for sequence 002. Establishing the initial connection with deep, hypnotic dub techno.",
    duration: "45:18",
    src: "https://cdn.formatglasgow.com/002/Form_at%20002%20-%20t.i.l.mp3",
    artwork: "sets/002",
    peaks: "https://cdn.formatglasgow.com/002/Form_at%20002%20-%20t.i.l.json",
    sizeBytes: 108761280,
  },
  {
    id: "set-002-hubey",
    title: "Form:at 002",
    artist: "hubey",
    date: "2026-04-24",
    venue: "Find the red door, Glasgow",
    description:
      "Mid-sequence escalation. Elevating the frequency with a high-energy blend of acid, electro, and driving grooves that took total control of the dancefloor.",
    duration: "1:31:55",
    src: "https://cdn.formatglasgow.com/002/Form_at%20002%20-%20hubey.mp3",
    artwork: "sets/002",
    peaks: "https://cdn.formatglasgow.com/002/Form_at%20002%20-%20hubey.json",
    sizeBytes: 220613760,
  },
  {
    id: "set-002-brandon-lee-vear",
    title: "Form:at 002",
    artist: "Brandon Lee Vear",
    date: "2026-04-24",
    venue: "Find the red door, Glasgow",
    description:
      "External operator integrated. A two-hour sustained transmission of deep, hypnotic techno, locking the dancefloor into a continuous loop during peak system hours.",
    duration: "2:01:55",
    src: "https://cdn.formatglasgow.com/002/Form_at%20002%20-%20Brandon%20Lee%20Vear.mp3.mp3",
    artwork: "sets/002",
    peaks: "https://cdn.formatglasgow.com/002/Form_at%20002%20-%20Brandon%20Lee%20Vear.mp3.json",
    sizeBytes: 292611840,
  },
  {
    id: "set-002-julz-lever",
    title: "Form:at 002",
    artist: "Julz Lever",
    date: "2026-04-24",
    venue: "Find the red door, Glasgow",
    description:
      "Closing protocol for sequence 002. High-fidelity techno pushing the system's architecture to its absolute limit.",
    duration: "1:39:30",
    src: "https://cdn.formatglasgow.com/002/Form_at%20002%20-%20Julz%20Lever.mp3",
    artwork: "sets/002",
    peaks: "https://cdn.formatglasgow.com/002/Form_at%20002%20-%20Julz%20Lever.json",
    sizeBytes: 238804800,
  },
];
